# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Bu_CH.py
# Created on: 2020-08-21 08:41:28.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
foehnhjahr = "N:\\Projekte\\050-059\\FP_CCW\\RASTER\\foehnhjahr"
lithonew7g = "N:\\Projekte\\050-059\\FP_CCW\\RASTER\\lithonew7g"
litrecnew7g = "D:\\temp\\temp.gdb\\litrecnew7g"
dhm25 = "N:\\Projekte\\050-059\\59_01_Klimaprojekt BAFU_WSL\\GIS\\IMPORT\\SWISSTOPO\\DHM25\\dhm25"
dhmrecloGr = "D:\\temp\\temp.gdb\\dhmrecloGr"
litho7dhmclass = "D:\\temp\\temp.gdb\\litho7dhmclass"
dhmrecl = "D:\\temp\\temp.gdb\\dhmrecl"
StandortregionenCH20160111_shp = "N:\\Projekte\\050-059\\FP_CCW\\VEKTOR\\StandortregionenCH20160111.shp"
StandortregionenCH20160111 = StandortregionenCH20160111_shp
StandortregionenCH20160111_2 = StandortregionenCH20160111
rbubin = "D:\\temp\\temp.gdb\\rbubin"
buareal = "D:\\temp\\temp.gdb\\buareal"
buareal1 = "D:\\temp\\temp.gdb\\buareal1"
litho7gbu = "D:\\temp\\temp.gdb\\litho7gbu"
foehnhjahr__4_ = "D:\\temp\\temp.gdb\\foehnhjahr"
fhjahrmean = "D:\\temp\\temp.gdb\\fhjahrmean"
lfhjahrmean = "D:\\temp\\temp.gdb\\lfhjahrmean"
fhjahrmax = "D:\\temp\\temp.gdb\\fhjahrmax"
lfhjahrmax = "D:\\temp\\temp.gdb\\lfhjahrmax"
buv12_fhj = "N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Einflussfaktoren\\heute\\buv12_fhj"
ns_jja = "N:\\Projekte\\050-059\\FP_CCW\\RASTER\\ns_jja"
ns_jja__3_ = "D:\\temp\\temp.gdb\\ns_jja"
nsjjamean = "D:\\temp\\temp.gdb\\nsjjamean"
lnsjjamean = "D:\\temp\\temp.gdb\\lnsjjamean"
nsjjamin = "D:\\temp\\temp.gdb\\nsjjamin"
lnsjjamin = "D:\\temp\\temp.gdb\\lnsjjamin"
buv12_nsjja = "N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Einflussfaktoren\\heute\\buv12_nsjja"
lfjahr = "N:\\Projekte\\050-059\\FP_CCW\\RASTER\\lfjahr"
lfjahr__3_ = "D:\\temp\\temp.gdb\\lfjahr"
lfjahrmean = "D:\\temp\\temp.gdb\\lfjahrmean"
llfjahrmean = "D:\\temp\\temp.gdb\\llfjahrmean"
lfjahrmin = "D:\\temp\\temp.gdb\\lfjahrmin"
llfjahrmin = "D:\\temp\\temp.gdb\\llfjahrmin"
buv12_lfj = "N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Einflussfaktoren\\heute\\buv12_lfj"
kontjahr1000 = "N:\\Projekte\\050-059\\FP_CCW\\RASTER\\kontjahr1000"
kontjahr1000__3_ = "D:\\temp\\temp.gdb\\kontjahr1000"
kontjahr1000mean = "D:\\temp\\temp.gdb\\kontjahr1000mean"
lkontjahr1000mean = "D:\\temp\\temp.gdb\\lkontjahr1000mean"
kontjahr1000max = "D:\\temp\\temp.gdb\\kontjahr1000max"
lkontjahr1000max = "D:\\temp\\temp.gdb\\lkontjahr1000max"
buv12_knt10 = "N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Einflussfaktoren\\heute\\buv12_knt10"
etap8110y = "RASTER\\etap8110y"
etap8110 = "D:\\temp\\temp.gdb\\etap8110"
etapmean = "D:\\temp\\temp.gdb\\etapmean"
letapmean = "D:\\temp\\temp.gdb\\letapmean"
etapmin = "D:\\temp\\temp.gdb\\etapmin"
letapmin = "D:\\temp\\temp.gdb\\letapmin"
buv12_etap = "N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Einflussfaktoren\\heute\\buv12_etap"
lfdkls = "RASTER\\lfdkls"
lfd = "D:\\temp\\temp.gdb\\lfd"
lfdmean = "D:\\temp\\temp.gdb\\lfdmean"
llfdmean = "D:\\temp\\temp.gdb\\llfdmean"
lfdmax = "D:\\temp\\temp.gdb\\lfdmax"
llfdmax = "D:\\temp\\temp.gdb\\llfdmax"
buv12_lfd = "N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Einflussfaktoren\\heute\\buv12_lfd"
Bu_V12_heute = "N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Bu_V12_heute"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "D:\\temp\\tempFGB.gdb"
arcpy.env.snapRaster = "D:\\CHGIS\\RASTER\\DHM25\\dhm25"
arcpy.env.extent = "479987.5 61987.5 865012.5 302012.5"
arcpy.env.cellSize = "25"
arcpy.env.mask = ""
arcpy.env.workspace = "D:\\temp\\tempFGB.gdb"

# Process: Reclassify (4)
arcpy.gp.Reclassify_sa(lithonew7g, "VALUE", "0 NODATA;1 1;2 2;3 3;4 4;5 5;6 6;7 7", litrecnew7g, "DATA")

# Process: Reclassify (3)
arcpy.gp.Reclassify_sa(dhm25, "Value", "193 800 1;800 1300 1;1300 4629 NODATA", dhmrecloGr, "DATA")

# Process: Times (11)
arcpy.gp.Times_sa(litrecnew7g, dhmrecloGr, litho7dhmclass)

# Process: Reclassify
arcpy.gp.Reclassify_sa(dhm25, "Value", "193 800 NODATA;800 1300 1;1300 4629 NODATA", dhmrecl, "DATA")

# Process: Add Field
arcpy.AddField_management(StandortregionenCH20160111_shp, "BuBIN", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(StandortregionenCH20160111, "BuBIN", "x", "VB", "if [Buchenarea]= \"mit Buche\" then\\nx = 1\\nelse\\nx = 0\\nend if")

# Process: Feature to Raster
arcpy.FeatureToRaster_conversion(StandortregionenCH20160111_2, "BuBIN", rbubin, "25")

# Process: Times
arcpy.gp.Times_sa(dhmrecl, rbubin, buareal)

# Process: Reclassify (2)
arcpy.gp.Reclassify_sa(buareal, "VALUE", "0 NODATA;1 1", buareal1, "DATA")

# Process: Times (10)
arcpy.gp.Times_sa(litrecnew7g, buareal1, litho7gbu)

# Process: Times (2)
arcpy.gp.Times_sa(foehnhjahr, buareal1, foehnhjahr__4_)

# Process: Zonal Statistics (2)
arcpy.gp.ZonalStatistics_sa(litho7gbu, "VALUE", foehnhjahr__4_, fhjahrmean, "MEAN", "DATA")

# Process: Zonal Statistics (10)
arcpy.gp.ZonalStatistics_sa(litho7dhmclass, "VALUE", fhjahrmean, lfhjahrmean, "MAXIMUM", "DATA")

# Process: Zonal Statistics
arcpy.gp.ZonalStatistics_sa(litho7gbu, "VALUE", foehnhjahr__4_, fhjahrmax, "MAXIMUM", "DATA")

# Process: Zonal Statistics (9)
arcpy.gp.ZonalStatistics_sa(litho7dhmclass, "VALUE", fhjahrmax, lfhjahrmax, "MAXIMUM", "DATA")

# Process: Raster Calculator (5)
arcpy.gp.RasterCalculator_sa("Con(\"%foehnhjahr%\"<=\"%lfhjahrmean%\",1,Con(\"%foehnhjahr%\">=\"%lfhjahrmax%\",0,1-(\"%foehnhjahr%\"-\"%lfhjahrmean%\")*1/(\"%lfhjahrmax%\"-\"%lfhjahrmean%\")))", buv12_fhj)

# Process: Times (3)
arcpy.gp.Times_sa(ns_jja, buareal1, ns_jja__3_)

# Process: Zonal Statistics (6)
arcpy.gp.ZonalStatistics_sa(litho7gbu, "VALUE", ns_jja__3_, nsjjamean, "MEAN", "DATA")

# Process: Zonal Statistics (12)
arcpy.gp.ZonalStatistics_sa(litho7dhmclass, "VALUE", nsjjamean, lnsjjamean, "MAXIMUM", "DATA")

# Process: Zonal Statistics (5)
arcpy.gp.ZonalStatistics_sa(litho7gbu, "VALUE", ns_jja__3_, nsjjamin, "MINIMUM", "DATA")

# Process: Zonal Statistics (11)
arcpy.gp.ZonalStatistics_sa(litho7dhmclass, "VALUE", nsjjamin, lnsjjamin, "MAXIMUM", "DATA")

# Process: Raster Calculator (7)
arcpy.gp.RasterCalculator_sa("Con(\"%ns_jja%\">=\"%lnsjjamean%\",1,Con(\"%ns_jja%\"<=\"%lnsjjamin%\",0,0+(\"%ns_jja%\"-\"%lnsjjamin%\")*1/(\"%lnsjjamean%\"-\"%lnsjjamin%\")))", buv12_nsjja)

# Process: Times (5)
arcpy.gp.Times_sa(lfjahr, buareal1, lfjahr__3_)

# Process: Zonal Statistics (8)
arcpy.gp.ZonalStatistics_sa(litho7gbu, "VALUE", lfjahr__3_, lfjahrmean, "MEAN", "DATA")

# Process: Zonal Statistics (14)
arcpy.gp.ZonalStatistics_sa(litho7dhmclass, "VALUE", lfjahrmean, llfjahrmean, "MAXIMUM", "DATA")

# Process: Zonal Statistics (7)
arcpy.gp.ZonalStatistics_sa(litho7gbu, "VALUE", lfjahr__3_, lfjahrmin, "MINIMUM", "DATA")

# Process: Zonal Statistics (13)
arcpy.gp.ZonalStatistics_sa(litho7dhmclass, "VALUE", lfjahrmin, llfjahrmin, "MAXIMUM", "DATA")

# Process: Raster Calculator (8)
arcpy.gp.RasterCalculator_sa("Con(\"%lfjahr%\">=\"%llfjahrmean%\",1,Con(\"%lfjahr%\"<=\"%llfjahrmin%\",0,0+(\"%lfjahr%\"-\"%llfjahrmin%\")*1/(\"%llfjahrmean%\"-\"%llfjahrmin%\")))", buv12_lfj)

# Process: Times (6)
arcpy.gp.Times_sa(kontjahr1000, buareal1, kontjahr1000__3_)

# Process: Zonal Statistics (4)
arcpy.gp.ZonalStatistics_sa(litho7gbu, "VALUE", kontjahr1000__3_, kontjahr1000mean, "MEAN", "DATA")

# Process: Zonal Statistics (16)
arcpy.gp.ZonalStatistics_sa(litho7dhmclass, "VALUE", kontjahr1000mean, lkontjahr1000mean, "MAXIMUM", "DATA")

# Process: Zonal Statistics (3)
arcpy.gp.ZonalStatistics_sa(litho7gbu, "VALUE", kontjahr1000__3_, kontjahr1000max, "MAXIMUM", "DATA")

# Process: Zonal Statistics (15)
arcpy.gp.ZonalStatistics_sa(litho7dhmclass, "VALUE", kontjahr1000max, lkontjahr1000max, "MAXIMUM", "DATA")

# Process: Raster Calculator (6)
arcpy.gp.RasterCalculator_sa("Con(\"%kontjahr1000%\"<=\"%lkontjahr1000mean%\",1,Con(\"%kontjahr1000%\">=\"%lkontjahr1000max%\",0,1-(\"%kontjahr1000%\"-\"%lkontjahr1000mean%\")*1/(\"%lkontjahr1000max%\"-\"%lkontjahr1000mean%\")))", buv12_knt10)

# Process: Times (4)
arcpy.gp.Times_sa(etap8110y, buareal1, etap8110)

# Process: Zonal Statistics (18)
arcpy.gp.ZonalStatistics_sa(litho7gbu, "VALUE", etap8110, etapmean, "MEAN", "DATA")

# Process: Zonal Statistics (20)
arcpy.gp.ZonalStatistics_sa(litho7dhmclass, "VALUE", etapmean, letapmean, "MAXIMUM", "DATA")

# Process: Zonal Statistics (17)
arcpy.gp.ZonalStatistics_sa(litho7gbu, "VALUE", etap8110, etapmin, "MINIMUM", "DATA")

# Process: Zonal Statistics (19)
arcpy.gp.ZonalStatistics_sa(litho7dhmclass, "VALUE", etapmin, letapmin, "MAXIMUM", "DATA")

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("Con(\"%etap8110y%\">=\"%letapmean%\",1,Con(\"%etap8110y%\"<=\"%letapmin%\",0,0+(\"%etap8110y%\"-\"%letapmin%\")*1/(\"%letapmean%\"-\"%letapmin%\")))", buv12_etap)

# Process: Times (7)
arcpy.gp.Times_sa(lfdkls, buareal1, lfd)

# Process: Zonal Statistics (22)
arcpy.gp.ZonalStatistics_sa(litho7gbu, "VALUE", lfd, lfdmean, "MEAN", "DATA")

# Process: Zonal Statistics (24)
arcpy.gp.ZonalStatistics_sa(litho7dhmclass, "VALUE", lfdmean, llfdmean, "MAXIMUM", "DATA")

# Process: Zonal Statistics (21)
arcpy.gp.ZonalStatistics_sa(litho7gbu, "VALUE", lfd, lfdmax, "MAXIMUM", "DATA")

# Process: Zonal Statistics (23)
arcpy.gp.ZonalStatistics_sa(litho7dhmclass, "VALUE", lfdmax, llfdmax, "MAXIMUM", "DATA")

# Process: Raster Calculator (3)
arcpy.gp.RasterCalculator_sa("Con(\"%lfdkls%\"<=\"%llfdmean%\",1,Con(\"%lfdkls%\">=\"%llfdmax%\",0,1-(\"%lfdkls%\"-\"%llfdmean%\")*1/(\"%llfdmax%\"-\"%llfdmean%\")))", buv12_lfd)

# Process: Fuzzy Overlay (2)
arcpy.gp.FuzzyOverlay_sa("'N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Einflussfaktoren\\heute\\buv12_fhj';'N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Einflussfaktoren\\heute\\buv12_nsjja';'N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Einflussfaktoren\\heute\\buv12_lfj';'N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Einflussfaktoren\\heute\\buv12_knt10';'N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Einflussfaktoren\\heute\\buv12_etap';'N:\\Projekte\\050-059\\59 KlimaprojektBAFUOekogramme\\59_09_FP2016_TeilA\\GIS\\Version 11\\Buche_V12\\Einflussfaktoren\\heute\\buv12_lfd'", Bu_V12_heute, "GAMMA", "0.9")

